[v1]
"cargo-contract 3.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-contract"]
"cargo-dylint 2.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-dylint"]
"contracts-node 0.35.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["substrate-contracts-node"]
"dylint-link 2.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dylint-link"]
"ink-lsp-server 0.2.15 (registry+https://github.com/rust-lang/crates.io-index)" = ["ink-lsp-server"]
"lsp-ai 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsp-ai"]
