[org/xfce/mousepad/state/application]
session=['1;;+file:///home/jondaw/Documents/Projects/nix-hypr/home/.cargo/.crates.toml']

[org/xfce/mousepad/state/window]
maximized=true
fullscreen=false

[org/xfce/mousepad/preferences/view]
word-wrap=true
