github.com:
    users:
        thejondaw:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: thejondaw
