# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/34ab9a00-2be1-4d33-a330-4bfc83f3f701";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/86939b60-6005-4720-b765-f334857ecaf4";

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/34ab9a00-2be1-4d33-a330-4bfc83f3f701";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1155-A952";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/34ab9a00-2be1-4d33-a330-4bfc83f3f701";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/34ab9a00-2be1-4d33-a330-4bfc83f3f701";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/34ab9a00-2be1-4d33-a330-4bfc83f3f701";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/34ab9a00-2be1-4d33-a330-4bfc83f3f701";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/34ab9a00-2be1-4d33-a330-4bfc83f3f701";
      fsType = "btrfs";
      options = [ "subvol=@varlog" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/39cefaec-232c-452f-b9d2-56aa1c97dd4b"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
